# Generated by Django 5.1.5 on 2025-02-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_subscribers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email', 'category')},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='username',
        ),
    ]
