# Generated by Django 5.1.5 on 2025-02-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
