# Generated by Django 5.1.5 on 2025-02-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
